# .github/workflows/sync.yml
name: Rebase Upstream
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"  # run once a day
  workflow_dispatch:   # run manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 15  # greater than the number of commits you made
    - uses: imba-tjd/rebase-upstream-action@master
  tag:
    needs: sync
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Auto Tagger
        uses: VegetableGarden/beet@0.0.3
        with:
          minor-version: 12
